# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT License"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/jdawg3636/ICBM/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="icbm" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.7.0" #mandatory

 # A display name for the mod
displayName="Intercontinental Ballistic Redux" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://icbm.jdawg3636.com/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="intercontinental-ballistic-redux-banner.png" #optional

# A text field displayed in the mod UI (#optional)
#credits='''
#'''

# A text field displayed in the mod UI
authors="jdawg3636" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Intercontinental Ballistic Redux is a Minecraft Mod that adds over twenty custom explosives, each of which are also available as missiles, minecarts, and sometimes even grenades. Some of the explosions have some pretty exotic effects, including nuclear fallout, contagious virus deployment, and all-consuming black holes! Combined with a few added features like poisonous spikes and player tracking, the mod creates an utterly unique experience that strikes the perfect balance of pushing boundaries without losing the spirit of the vanilla game.
'''
